name: "Hello Actions"
description: "First action to greet someone"
author: "https://github.com/shashi278"

inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "World"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"
