name: Deploy on PyPI
on:
  release:
    types: [published]
  
jobs:
  build:
    name: Deployment Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        
      - name: Set up Python 3.x
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
          
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
        
      - uses: ./
        with:
          TOKEN: "pypi-AgEIcHlwaS5vcmcCJDJlNmM1NzUzLTYyZWEtNDg3YS1iMGZhLTkzNzI2NWJlNjM1YwACJXsicGVybWlzc2lvbnMiOiAidXNlciIsICJ2ZXJzaW9uIjogMX0AAAYgcXbq9BC1CZQdwjaEJMHbmXC2zVnYMV1Qi1wi3tfNIkM"
